// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkEmailOrContactExists = `-- name: CheckEmailOrContactExists :execrows
select id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code from users
where email=$1 or contact=$2
limit 1
`

type CheckEmailOrContactExistsParams struct {
	Email   string `json:"email"`
	Contact string `json:"contact"`
}

func (q *Queries) CheckEmailOrContactExists(ctx context.Context, arg CheckEmailOrContactExistsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, checkEmailOrContactExists, arg.Email, arg.Contact)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const checkForContact = `-- name: CheckForContact :one
select id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code from users 
where contact = $1
and id <> $2
`

type CheckForContactParams struct {
	Contact string    `json:"contact"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) CheckForContact(ctx context.Context, arg CheckForContactParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, checkForContact, arg.Contact, arg.ID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.Contact,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Department,
		&i.EmpCode,
	)
	return i, err
}

const countOfSearchUsers = `-- name: CountOfSearchUsers :one
select count(*) from users 
where concat(full_name,email,contact, user_type, emp_code) like '%' || $1 || '%'
`

// count of search emp
func (q *Queries) CountOfSearchUsers(ctx context.Context, dollar_1 sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOfSearchUsers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByDepartment = `-- name: CountUsersByDepartment :one
select count(*) from users 
where department = $1
`

// count users by department
func (q *Queries) CountUsersByDepartment(ctx context.Context, department string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByDepartment, department)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNewUser = `-- name: CreateNewUser :one
insert into users (
    full_name,
    email,
    password,
    contact,
    user_type,
    department,
    emp_code
) values (
    $1,$2,$3,$4,$5,$6,$7
) returning id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code
`

type CreateNewUserParams struct {
	FullName   string `json:"full_name"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	Contact    string `json:"contact"`
	UserType   string `json:"user_type"`
	Department string `json:"department"`
	EmpCode    string `json:"emp_code"`
}

func (q *Queries) CreateNewUser(ctx context.Context, arg CreateNewUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createNewUser,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.Contact,
		arg.UserType,
		arg.Department,
		arg.EmpCode,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.Contact,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Department,
		&i.EmpCode,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
delete from users 
where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fetchAllUsers = `-- name: FetchAllUsers :many
select id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code from users 
order by created_at desc 
limit $1
offset $2
`

type FetchAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchAllUsers(ctx context.Context, arg FetchAllUsersParams) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, fetchAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Password,
			&i.Contact,
			&i.UserType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Department,
			&i.EmpCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmailOrContact = `-- name: GetUserByEmailOrContact :one
select id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code from users
where email=$1 or contact = $1
limit 1
`

func (q *Queries) GetUserByEmailOrContact(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailOrContact, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.Contact,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Department,
		&i.EmpCode,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
select id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code from users
where id = $1
limit 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.Contact,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Department,
		&i.EmpCode,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
/*
    full_name,
    email,
    password,
    contact,
    user_type,
    department,
    emp_code

*/

select id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code from users
where concat(full_name,email,contact, user_type, emp_code) like '%' || $3 || '%'
limit $1
offset $2
`

type SearchUsersParams struct {
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
	Column3 sql.NullString `json:"column_3"`
}

// search emp
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Password,
			&i.Contact,
			&i.UserType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Department,
			&i.EmpCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execresult
update users 
set full_name=$2,
contact=$3,
user_type=$4,
emp_code=$5,
updated_at = CURRENT_TIMESTAMP
where id=$1 
returning id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code
`

type UpdateUserParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Contact  string    `json:"contact"`
	UserType string    `json:"user_type"`
	EmpCode  string    `json:"emp_code"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Contact,
		arg.UserType,
		arg.EmpCode,
	)
}

const usersByDepartment = `-- name: UsersByDepartment :many
select id, full_name, email, password, contact, user_type, created_at, updated_at, department, emp_code from users 
where department = $1
group by id
order by created_at desc 
limit $2
offset $3
`

type UsersByDepartmentParams struct {
	Department string `json:"department"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

// fetch users by department
func (q *Queries) UsersByDepartment(ctx context.Context, arg UsersByDepartmentParams) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, usersByDepartment, arg.Department, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Password,
			&i.Contact,
			&i.UserType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Department,
			&i.EmpCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
